export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILED = "GET_POSTS_FAILED";

export const GET_ADS_DETAILS = "GET_ADS_DETAILS";
export const GET_ADS_DETAILS_SUCCESS = "GET_ADS_DETAILS_SUCCESS";
export const GET_ADS_DETAILS_FAILED = "GET_ADS_DETAILS_FAILED";

export const LOAD_MORE = "LOAD_MORE";
export const LOAD_MORE_SUCCESS = "LOAD_MORE_SUCCESS";
export const LOAD_MORE_FAILED = "LOAD_MORE_FAILED";

export const LIVE_SEARCH = "LIVE_SEARCH";
export const LIVE_SEARCH_SUCCESS = "LIVE_SEARCH_SUCCESS";
export const LIVE_SEARCH_FAILED = "LIVE_SEARCH_FAILED";

export const GET_POST = "GET_POST";
export const POST_RECEIVED = "POST_RECEIVED";
export const POST_REQUEST_FAILED = "POST_REQUEST_FAILED";

export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILED = "UPDATE_POST_FAILED";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILED = "DELETE_POST_FAILED";

export const GET_PROFILE_ADS = "GET_PROFILE_ADS";
export const GET_PROFILE_ADS_SUCCESS = "GET_PROFILE_ADS_SUCCESS";
export const GET_PROFILE_ADS_FAILED = "GET_PROFILE_ADS_FAILED";

export const GET_METRO = "GET_METRO";
export const GET_METRO_SUCCESS = "GET_METRO_SUCCESS";
export const GET_METRO_FAILED = "GET_METRO_FAILED";

export const GET_CITY = "GET_CITY";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_FAILED = "GET_CITY_FAILED";

export const CREATE_RESUME = "CREATE_RESUME";
export const CREATE_RESUME_SUCCESS = "CREATE_RESUME_SUCCESS";
export const CREATE_RESUME_FAILED = "CREATE_RESUME_FAILED";

export const GET_RESUME = "GET_RESUME";
export const GET_RESUME_SUCCESS = "GET_RESUME_SUCCESS";
export const GET_RESUME_FAILED = "GET_RESUME_FAILED";

export const GET_RESUME_DETAILS = "GET_RESUME_DETAILS";
export const GET_RESUME_DETAILS_SUCCESS = "GET_RESUME_DETAILS_SUCCESS";
export const GET_RESUME_DETAILS_FAILED = "GET_RESUME_DETAILS_FAILED";

export const CREATE_EDUCATION_INFO = "CREATE_EDUCATION_INFO";
export const CREATE_EDUCATION_INFO_SUCCESS = "CREATE_EDUCATION_INFO_SUCCESS";
export const CREATE_EDUCATION_INFO_FAILED = "CREATE_EDUCATION_INFO_FAILED";

export const CREATE_EXPERIENCE_INFO = "CREATE_EXPERIENCE_INFO";
export const CREATE_EXPERIENCE_INFO_SUCCESS = "CREATE_EXPERIENCE_INFO_SUCCESS";
export const CREATE_EXPERIENCE_INFO_FAILED = "CREATE_EXPERIENCE_INFO_FAILED";

export const GET_EDUCATION = "GET_EDUCATION";
export const GET_EDUCATION_SUCCESS = "GET_EDUCATION_SUCCESS";
export const GET_EDUCATION_FAILED = "GET_EDUCATION_FAILED";
